//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class checklist_fase
    {
        public int id_checklist_fase { get; set; }
        public int id_checklist { get; set; }
        public int id_fase { get; set; }
        public Nullable<System.DateTime> data_inicio_fase { get; set; }
        public Nullable<System.DateTime> data_final_fase { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual usuario usuario1 { get; set; }
        public virtual tipo_fase tipo_fase { get; set; }
        public virtual checklist checklist { get; set; }
    }
}
