//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class endereco
    {
        public int id_endereco { get; set; }
        public Nullable<int> id_empresa { get; set; }
        public Nullable<int> id_cidade { get; set; }
        public string bairro { get; set; }
        public string logradrouro { get; set; }
        public Nullable<int> numero { get; set; }
        public string cep { get; set; }
        public string telefone { get; set; }
    
        public virtual cidade cidade { get; set; }
        public virtual empresa empresa { get; set; }
    }
}
