//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado
    {
        public estado()
        {
            this.cidade = new HashSet<cidade>();
            this.empresa = new HashSet<empresa>();
        }
    
        public int id_estado { get; set; }
        public string desc_estado { get; set; }
        public string sig_estado { get; set; }
        public int id_pais { get; set; }
    
        public virtual ICollection<cidade> cidade { get; set; }
        public virtual ICollection<empresa> empresa { get; set; }
    }
}
