//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class marca_veiculo
    {
        public marca_veiculo()
        {
            this.veiculo = new HashSet<veiculo>();
        }
    
        public int id_marca_veiculo { get; set; }
        public string desc_marca_veiculo { get; set; }
    
        public virtual ICollection<veiculo> veiculo { get; set; }
    }
}
