//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class permissao_usuario
    {
        public int id_permissao_usuario { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> id_tela { get; set; }
        public Nullable<bool> ativo { get; set; }
    
        public virtual tela tela { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
