//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsiminasIpatingaEntities : DbContext
    {
        public UsiminasIpatingaEntities()
            : base("name=UsiminasIpatingaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<checklist_fase> checklist_fase { get; set; }
        public DbSet<cidade> cidade { get; set; }
        public DbSet<condutor> condutor { get; set; }
        public DbSet<cor_veiculo> cor_veiculo { get; set; }
        public DbSet<empresa> empresa { get; set; }
        public DbSet<endereco> endereco { get; set; }
        public DbSet<estado> estado { get; set; }
        public DbSet<marca_veiculo> marca_veiculo { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<permissao_usuario> permissao_usuario { get; set; }
        public DbSet<tela> tela { get; set; }
        public DbSet<tipo_acessorio> tipo_acessorio { get; set; }
        public DbSet<tipo_assoalho> tipo_assoalho { get; set; }
        public DbSet<tipo_carroceria> tipo_carroceria { get; set; }
        public DbSet<tipo_empresa> tipo_empresa { get; set; }
        public DbSet<tipo_fase> tipo_fase { get; set; }
        public DbSet<tipo_frete> tipo_frete { get; set; }
        public DbSet<tipo_produto> tipo_produto { get; set; }
        public DbSet<tipo_qualidade_item> tipo_qualidade_item { get; set; }
        public DbSet<tipo_transporte> tipo_transporte { get; set; }
        public DbSet<tipo_usuario> tipo_usuario { get; set; }
        public DbSet<tipo_veiculo> tipo_veiculo { get; set; }
        public DbSet<usuario> usuario { get; set; }
        public DbSet<veiculo> veiculo { get; set; }
        public DbSet<checklist> checklist { get; set; }
    }
}
