//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_fase
    {
        public tipo_fase()
        {
            this.checklist_fase = new HashSet<checklist_fase>();
        }
    
        public int id_fase { get; set; }
        public string desc_fase { get; set; }
    
        public virtual ICollection<checklist_fase> checklist_fase { get; set; }
    }
}
