//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_qualidade_item
    {
        public int id_tipo_qualidade_item { get; set; }
        public string desc_qualidade_item { get; set; }
    
        public virtual tipo_qualidade_item tipo_qualidade_item1 { get; set; }
        public virtual tipo_qualidade_item tipo_qualidade_item2 { get; set; }
        public virtual tipo_qualidade_item tipo_qualidade_item11 { get; set; }
        public virtual tipo_qualidade_item tipo_qualidade_item3 { get; set; }
    }
}
