//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class veiculo
    {
        public veiculo()
        {
            this.checklist = new HashSet<checklist>();
        }
    
        public string placa { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<byte> idc_reprovado { get; set; }
        public string modelo { get; set; }
        public Nullable<int> id_cor_veiculo { get; set; }
        public Nullable<int> id_marca_veiculo { get; set; }
        public string placa_mercosul { get; set; }
    
        public virtual cor_veiculo cor_veiculo { get; set; }
        public virtual marca_veiculo marca_veiculo { get; set; }
        public virtual ICollection<checklist> checklist { get; set; }
    }
}
